tools = { wally = "UpliftGames/wally@0.3.2" , rojo = "rojo-rbx/rojo@7.5.1" }
[package]
name = "TbeyazT/game-starter"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.6"
Loader = "sleitnick/loader@2.0.0"
Dumpster = "kinqandi/dumpster@0.3.7"
Observe = "kinqandi/observe@1.0.3"
Signal = "sleitnick/signal@2.0.1"
Input = "sleitnick/input@2.3.0"
TaskQueue = "sleitnick/task-queue@0.1.1"
TableUtil = "sleitnick/table-util@1.2.1"
WaitFor = "sleitnick/wait-for@1.0.0"
Promise = "evaera/promise@4.0.0"
Timer = "sleitnick/timer@1.1.2"